services:
  web:
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: ./backend/Dockerfile # билд зависимостей 
    command: uv run gunicorn app.routes.app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - media_data:/mini_shop_db/media
    # не прокидываем порты, этим будет заниматься nginx
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /mini_shop_db/app

        - action: sync
          path: ./backend/media
          target: /mini_shop_db/media

        - action: rebuild
          path: .env

        - action: rebuild
          path: ./backend/alembic
    depends_on:
      # старт только когда запустилась бд
      db:
        condition: service_healthy

  frontend:
    image: node:20-slim
    container_name: vite_frontend
    working_dir: /mini_shop_db/frontend
    # 1. Сначала ставим зависимости (если папка node_modules пуста), а потом запускаем dev-сервер
    command: sh -c "npm install && npm run build"
    # Монтируем корень проекта, чтобы Node видел папку frontend
    volumes:
      - .:/mini_shop_db
      - dist:/mini_shop_db/frontend/dist
      # Анонимный volume перекрывает хостовый node_modules —
      # контейнер установит свои нативные бинарники (esbuild, rollup и т.д.)
      - /mini_shop_db/frontend/node_modules
    develop:
      watch:
        # Следим за изменениями фронта для hot-reload
        - action: sync
          path: ./frontend
          target: /mini_shop_db/frontend

  db:
    image: postgres:16.4
    container_name: postgres_db
    restart: always # упала — Docker сам поднимет
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASS}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data # данные переживут down
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 3

  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      SCRIPT_NAME: /pgadmin
    depends_on:
      # старт только когда запустилась бд
      db:
        condition: service_healthy

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      # Образ сам всё прочитает и запросит сертификаты на этот email
      - CERTBOT_EMAIL=${DOMAIN_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Важно: конфиг монтируем именно в папку user_conf.d
      - ./backend/nginx/nginx.conf:/etc/nginx/user_conf.d/app.conf:ro
      - media_data:/var/www/media:ro
      - letsencrypt_data:/etc/letsencrypt # Здесь докер сам будет хранить сертификаты
      - dist:/var/www/dist
    depends_on:
      - web
      - frontend
volumes:
  pg_data:
  letsencrypt_data:
  media_data:
  dist:
