services:
  web:
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: ./backend/Dockerfile # билд зависимостей 
    command: uv run gunicorn app.routes.app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - media_data:/mini_shop_db/media
    depends_on:
      # старт только когда запустилась бд
      db:
        condition: service_healthy
    networks:
      - backend_net
      - frontend_net

  frontend:
    image: node:22-slim
    working_dir: /mini_shop_db/frontend
    # 1. Сначала ставим зависимости (если папка node_modules пуста), а потом запускаем dev-сервер
    command: sh -c "npm install && npm run build"
    # Монтируем корень проекта, чтобы Node видел папку frontend
    volumes:
      - .:/mini_shop_db
      - dist:/mini_shop_db/frontend/dist
      # Анонимный volume перекрывает хостовый node_modules —
      # контейнер установит свои нативные бинарники (esbuild, rollup и т.д.)
      - /mini_shop_db/frontend/node_modules
    networks:
      - frontend_net

  db:
    image: postgres:16.4
    restart: always # упала — Docker сам поднимет
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data # данные переживут down
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - backend_net

  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      SCRIPT_NAME: /pgadmin
    depends_on:
      # старт только когда запустилась бд
      db:
        condition: service_healthy
    networks:
      - backend_net
      - frontend_net

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      # Образ сам всё прочитает и запросит сертификаты на этот email
      - CERTBOT_EMAIL=${DOMAIN_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Важно: конфиг монтируем именно в папку user_conf.d
      - ./backend/nginx/nginx.conf:/etc/nginx/user_conf.d/app.conf:ro
      - media_data:/var/www/media:ro
      - letsencrypt_data:/etc/letsencrypt # Здесь докер сам будет хранить сертификаты
      - dist:/var/www/dist
    depends_on:
      - web
      - frontend
    networks:
      - frontend_net
volumes:
  pg_data:
  letsencrypt_data:
  media_data:
  dist:

networks:
  backend_net:
  frontend_net:

