services:
  test_db:
    image: postgres:16.4
    container_name: test_postgres_db
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASS}
      POSTGRES_DB: ${DB__NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 3
  test_web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.test
    depends_on:
      # старт только когда запустилась бд
      test_db:
        condition: service_healthy
    command: uv run pytest -s -vv
