upstream fastapi_ecommerce {
    server web:8000;
}

upstream vite_frontend {
    server frontend:3000;
}

server {
    listen 443 ssl;
    server_name minishopdb.mooo.com;

    sendfile on;
    client_max_body_size 10m;  # без этого nginx режет загрузку файлов на 1 МБ

    # Эти строки НУЖНЫ! Образ jonasal/nginx-certbot сканирует ssl_certificate_key
    # чтобы понять, какой cert-name использовать и для каких server_name запросить сертификат.
    # "minishopdb.mooo.com" — это cert-name, совпадает с доменом для простоты.
    ssl_certificate     /etc/letsencrypt/live/minishopdb.mooo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/minishopdb.mooo.com/privkey.pem;

    # Рекомендуемые SSL-настройки
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    # Глобальные заголовки для проксирования
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Все запросы к интерфейсу идут на Vite
    location / {
        proxy_pass http://vite_frontend;
        # Поддержка вебсокетов для Vite hot-reload
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Все запросы к бэкенду уходят на FastAPI
    location ~ ^/(api|docs|redoc|openapi.json) {
        proxy_pass http://fastapi_ecommerce;
        proxy_redirect off;
    }

    location ^~ /media/ {
        alias /var/www/media/;
    }
    location /pgadmin/ {
	proxy_pass http://pgadmin_ui:80;
    	proxy_set_header X-Script-Name /pgadmin;
    	proxy_set_header Host $host;
    	proxy_redirect off;
    }
}
