""".

Revision ID: a8e4220af9be
Revises: c418388bd210
Create Date: 2026-06-12 19:08:36.970084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e4220af9be'
down_revision: Union[str, Sequence[str], None] = 'c418388bd210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.add_column('orders', sa.Column('price_for_one', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('orders', sa.Column('product_id', sa.Uuid(), nullable=False))
    op.add_column('orders', sa.Column('amount', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'product_id')
    op.drop_column('orders', 'price_for_one')
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_for_one', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('check_amount_positive')),
    sa.CheckConstraint('price_for_one >= 0::numeric', name=op.f('check_price_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('order_items_product_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name=op.f('order_items_pkey'))
    )
    # ### end Alembic commands ###
