"""add authication columns + session table

Revision ID: 8f4450a407b1
Revises: 92fe2aa017f6
Create Date: 2026-06-10 15:34:52.571104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4450a407b1'
down_revision: Union[str, Sequence[str], None] = '92fe2aa017f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('hash_password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
