"""remove_unused_relationships

Revision ID: 941c9f018511
Revises: ca6d1c27b59a
Create Date: 2026-06-08 00:19:40.911607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "941c9f018511"
down_revision: Union[str, Sequence[str], None] = "ca6d1c27b59a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_unique_constraint(None, "products", ["category_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    op.alter_column(
        "products", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
