"""change authication to google

Revision ID: c62ca5484e77
Revises: ddd921e9617f
Create Date: 2026-06-12 13:16:38.573637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62ca5484e77'
down_revision: Union[str, Sequence[str], None] = 'ddd921e9617f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=256), nullable=False))
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('admin', 'user', 'creator', name='userrole', native_enum=False),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['google_id'])
    op.drop_column('users', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'user', 'creator', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'picture')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
