"""add total_price (orders table)

Revision ID: ca6d1c27b59a
Revises: 7dfd77909271
Create Date: 2026-06-07 11:07:01.086170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca6d1c27b59a"
down_revision: Union[str, Sequence[str], None] = "7dfd77909271"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "total_price")
    # ### end Alembic commands ###
