"""fix: weights on products table (fts)

Revision ID: 0550f5ec1f12
Revises: f1cb74cd42f1
Create Date: 2026-06-14 12:55:46.568056

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '0550f5ec1f12'
down_revision: Union[str, Sequence[str], None] = 'f1cb74cd42f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
