upstream fastapi_ecommerce {
    server web:8000;
}

upstream vite_frontend {
    server frontend:3000; # имя сервиса из compose и порт Vite
}

server {
    listen 80;
    server_name 127.0.0.1;

    # Все запросы к интерфейсу идут на Vite
    location / {
        proxy_pass http://vite_frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Важно для Vite: поддержка вебсокетов (чтобы работал hot-reload в браузере)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Все запросы к бэкенду (урлы, начинающиеся с /api или /docs) уходят на FastAPI
    location ~ ^/(api|docs|redoc|openapi.json) {
        proxy_pass http://fastapi_ecommerce;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /media/ {
        alias /var/www/media/;
    }
}